### ISSUE TITLE
[manta] performance improvement

### ISSUE THREAD

**Issue by zhenfeizhang** [Manta-Network/pallet-manta-pay#35]
try various optimizations to improve verification speed

**Comment by Dengjianping** [comment]
I just don't dive into it too much, and leave some comments below.

1. Avoid use heap memory or cloning, or allocate heap memory at just one time. Or look for fine-tuned crates like smallvec, memchr, etc.

   [example](https://github.com/Manta-Network/pallet-manta-pay/blob/calamari/src/coin.rs#L119):

   ```rust
   let buf: Vec<u8> = [value.to_le_bytes().as_ref(), k_bytes.clone().as_ref()].concat();
   ```

   Actually, there's no need to use `Vec`(it's allocated on heap), `value` is u64, `to_le_bytes` will generate a [u8; 8], and `k_bytes` is an constant array(length 32). So we can write this line like this:

   ```rust
   let mut buf = [0u8; 40]
   // copy value.to_le_bytes() and k_bytes
   ```

   

2. Use const feature with rust 1.51  or later and const function in rust stdlib

   [example](https://github.com/Manta-Network/pallet-manta-pay/blob/calamari/src/serdes.rs#L89):

   ```rust
   fn deserialize<R: Read, const PERDERSON_WINDOW_SIZE: usize, const PERDERSON_WINDOW_NUM: usize>(mut reader: R) -> Self {
   		let mut generators = [_; PERDERSON_WINDOW_NUM];
   		for _ in 0..len {
   			let mut gen = [_; PERDERSON_WINDOW_SIZE];
   			for _ in 0..window {
   				gen.push(EdwardsProjective::deserialize_unchecked(&mut reader).unwrap())
   			}
   			generators.push(gen);
   		}
   		let mut randomness_generator = [_; 252];
   		for _ in 0..252 {
   			randomness_generator
   				.push(EdwardsProjective::deserialize_unchecked(&mut reader).unwrap())
   		}
   
   		Self {
   			randomness_generator,
   			generators,
   		}
   	}
   ```

   

3. Use flamegraph to find out where is the bottleneck;

   https://github.com/flamegraph-rs/flamegraph

   https://github.com/jonhoo/inferno

4. The unofficial book might help.

   https://nnethercote.github.io/perf-book/title-page.html
