### ISSUE TITLE
Investigate introducing a scale factor to manta-pay pallet weight functions.

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/pallet-manta-pay#41]
* Investigate introducing a "scale factor" to manta-pay pallet weight functions.
* We are already benchmarking with a "typical" cloud instance, but this might be better to hit a "worst case scenario".

**Comment by stechu** [comment]
Talked to the Devs of some other Polkadot projects, they actually set up a bot to do this automatically.

**Comment by ghzlatarev** [comment]
> automatically

Do you mean the whole process? That we can do. was about to log it. We would just need to.
1. Run a build script
2. Run the benchmarking command
3. Copy the fife

But first we gotta create a Weights directory in our runtime where we can override all pallets' weights (including our own) with https://github.com/Manta-Network/Manta/issues/49.

And we'd need to manually copy the file to the manta-pay repo and open a pr there, Not sure if we can automate that.
